
Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vm.box_version = "20210210.0"
  
  config.vm.define "systemdOtus" do |systemdOtus|
    systemdOtus.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    systemdOtus.vm.hostname = "systemdOtus"
  config.vm.provision "shell",
  inline: "setenforce 0"
  config.vm.provision "shell",
  inline: "yum install -y epel-release && yum install -y spawn-fcgi php php-cli mod_fcgid"
  config.vm.provision "file", source: "spawn-fcgi", destination: "/tmp/spawn-fcgi"
  config.vm.provision "shell",
  inline: "mv /tmp/spawn-fcgi /etc/sysconfig/spawn-fcgi"
  config.vm.provision "file", source: "spawn-fcgi.service", destination: "/tmp/spawn-fcgi.service"
  config.vm.provision "shell",
  inline: "mv /tmp/spawn-fcgi.service /etc/systemd/system/spawn-fcgi.service"
  
   end
  
end
