
Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vm.box_version = "20210210.0"
  
   config.vm.define "systemdOtus" do |systemdOtus|
    systemdOtus.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    systemdOtus.vm.hostname = "systemdOtus"
  config.vm.provision "shell",
  inline: "setenforce 0"
  config.vm.provision "file", source: "watchlog.sh", destination: "/tmp/watchlog.sh"
  config.vm.provision "shell",
  inline: "mv /tmp/watchlog.sh /opt/watchlog.sh"
  config.vm.provision "shell",
  inline: "chmod +x /opt/watchlog.sh"
  config.vm.provision "file", source: "watchlog.service", destination: "/tmp/watchlog.service"
  config.vm.provision "shell",
  inline: "mv /tmp/watchlog.service /etc/systemd/system/watchlog.service"
  config.vm.provision "file", source: "watchlog.timer", destination: "/tmp/watchlog.timer"
  config.vm.provision "shell",
  inline: "mv /tmp/watchlog.timer /etc/systemd/system/watchlog.timer"
  config.vm.provision "file", source: "watchlog", destination: "/tmp/watchlog"
  config.vm.provision "shell",
  inline: "mv /tmp/watchlog /etc/sysconfig/watchlog"
  config.vm.provision "file", source: "watchlog.log", destination: "/tmp/watchlog.log"
  config.vm.provision "shell",
  inline: "mv /tmp/watchlog.log /var/log/watchlog.log"
  end
  
end
