Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream8"
  config.vm.box_version = "20210210.0"
  
  config.vm.define "systemdOtus" do |systemdOtus|
    systemdOtus.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    systemdOtus.vm.hostname = "systemdOtus"
  config.vm.provision "shell",
  inline: "setenforce 0"
  config.vm.provision "shell",
  inline: "yum install -y epel-release && yum install -y httpd"
  config.vm.provision "file", source: "httpd@.service", destination: "/tmp/httpd@.service"
  config.vm.provision "shell",
  inline: "mv /tmp/httpd@.service /usr/lib/systemd/system/httpd@.service"
  config.vm.provision "file", source: "httpd-first", destination: "/tmp/httpd-first"
  config.vm.provision "shell",
  inline: "mv /tmp/httpd-first /etc/sysconfig/httpd-first"
  config.vm.provision "file", source: "httpd-second", destination: "/tmp/httpd-second"
  config.vm.provision "shell",
  inline: "mv /tmp/httpd-second /etc/sysconfig/httpd-second"
  config.vm.provision "shell",
  inline: "cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/first.conf"
  config.vm.provision "shell",
  inline: "cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/second.conf"
  config.vm.provision "shell", path: "httpd.sh"
  
   end
  
end
